# Be sure to restart your server when you modify this file.

defaults: &defaults
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  airbrake_host: <%= ENV['AIRBRAKE_HOST'] %>
  airbrake_project_key: <%= ENV['AIRBRAKE_PROJECT_KEY'] || ENV['AIRBRAKE_API_KEY']%>
  pg_host: <%= ENV['PG_HOST'] %>
  pg_port: <%= ENV['PG_PORT'] %>
  pg_database: <%= ENV['PG_DATABASE'] %>
  pg_username: <%= ENV['PG_USERNAME'] %>
  pg_password: <%= ENV['PG_PASSWORD'] %>
  pg_users_host: <%= ENV['PG_USERS_HOST'] || ENV['PG_HOST'] %>
  pg_users_port: <%= ENV['PG_USERS_PORT'] || ENV['PG_PORT'] %>
  pg_users_database: <%= ENV['PG_USERS_DATABASE'] %>
  pg_users_username: <%= ENV['PG_USERS_USERNAME'] || ENV['PG_USERNAME'] %>
  pg_users_password: <%= ENV['PG_USERS_PASSWORD'] || ENV['PG_PASSWORD'] %>
  address_facade_server: <%= ENV['ADDRESS_FACADE_SERVER'] %>
  address_facade_port: <%= ENV['ADDRESS_FACADE_PORT'] %>
  address_facade_client_id: <%= ENV['ADDRESS_FACADE_CLIENT_ID'] %>
  address_facade_key: <%= ENV['ADDRESS_FACADE_KEY'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] || 'eu-west-1' %>
  # Please note, this is actually a string which is evaluated when used, and not some
  # ruby code which has not been properly tagged.
  exemptions_expire_after: 3.years - 1.day

development:
  <<: *defaults
  secret_key_base: 5b456be22062e002d232c2aed8996d48a47bbd6916c34c62d5eb0584769a2611c1f0dd83a6220f5d4d682b521709b3f944cf112cb5a1a45b1528dbfe361c2f01
  address_facade_server: <%= ENV['ADDRESS_FACADE_TEST_SERVER'] %>
  address_facade_port: <%= ENV['ADDRESS_FACADE_TEST_PORT'] %>

test:
  <<: *defaults
  secret_key_base: a7e6e3347850a7301d756bc63d95cc32c6dc1a425d93f04ec2b960b8519c67953919c17fdd904f35792be3ffe88acf87f075f2f78351757abad2b142787ca3409
  address_facade_server: <%= ENV['ADDRESS_FACADE_TEST_SERVER'] %>
  address_facade_port: <%= ENV['ADDRESS_FACADE_TEST_PORT'] %>

production: &production
  <<: *defaults
