# Be sure to restart your server when you modify this file.

defaults: &defaults
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  airbrake_host: <%= ENV['AIRBRAKE_HOST'] %>
  airbrake_project_key: <%= ENV['AIRBRAKE_BO_PROJECT_KEY']%>
  pg_host: <%= ENV['PG_HOST'] %>
  pg_port: <%= ENV['PG_PORT'] %>
  pg_database: <%= ENV['PG_DATABASE'] %>
  pg_username: <%= ENV['PG_USERNAME'] %>
  pg_password: <%= ENV['PG_PASSWORD'] %>
  aws_access_key_id: <%= ENV['FRA_AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['FRA_AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['FRA_AWS_REGION'] || 'eu-west-1' %>
  session_timeout_minutes: <%= ENV.fetch("SESSION_TIMEOUT_MINUTES", 480).to_i %>

development:
  <<: *defaults
  secret_key_base: 5b456be22062e002d232c2aed8996d48a47bbd6916c34c62d5eb0584769a2611c1f0dd83a6220f5d4d682b521709b3f944cf112cb5a1a45b1528dbfe361c2f01

test:
  <<: *defaults
  secret_key_base: a7e6e3347850a7301d756bc63d95cc32c6dc1a425d93f04ec2b960b8519c67953919c17fdd904f35792be3ffe88acf87f075f2f78351757abad2b142787ca3409

production: &production
  <<: *defaults
